trigger:
  branches:
    include:
    - main
pr:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  goVersion: '1.20.5'

steps:
- task: GoTool@0
  inputs:
    version: '$(goVersion)'
  displayName: 'Install Go'

- script: |
    go version
    go get -v -t -d ./...
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
    go build -v .
  displayName: 'Get dependencies, then build'
  env:
    DSN: $(DSN)
    FEE_FROM_1_TO_10000: $(FEE_FROM_1_TO_10000)
    RATE_LIMIT: $(RATE_LIMIT)
    GIN_MODE: $(GIN_MODE)

- script: |
    go test -v ./routers -run=TestRateLimitingMiddlewareOnGet
  displayName: 'Run rate-limiter tests'
  env:
    DSN: $(DSN)
    FEE_FROM_1_TO_10000: $(FEE_FROM_1_TO_10000)
    RATE_LIMIT: $(RATE_LIMIT)
    GIN_MODE: $(GIN_MODE)

- script: |
    go test -v -tags=rateLimit ./routers
  displayName: 'Run router tests'
  env:
    DSN: $(DSN)
    FEE_FROM_1_TO_10000: $(FEE_FROM_1_TO_10000)
    RATE_LIMIT: $(RATE_LIMIT)
    GIN_MODE: $(GIN_MODE)
